name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      # Client-side variables (public)
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
      NEXT_PUBLIC_GA4_ID: ${{ secrets.NEXT_PUBLIC_GA4_ID }}
      NEXT_PUBLIC_CALENDLY_LINK: ${{ secrets.NEXT_PUBLIC_CALENDLY_LINK }}
      NEXT_PUBLIC_CALENDLY_EMBED_URL: ${{ secrets.NEXT_PUBLIC_CALENDLY_EMBED_URL }}
      
      # Server-side variables (protected)
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      ZAPIER_WEBHOOK_URL: ${{ secrets.ZAPIER_WEBHOOK_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug Node Modules
        run: |
          echo "Node modules directory contents:"
          ls -la node_modules
          echo "Next.js version:"
          npx next --version

      - name: Run linting
        run: npm run lint

      - name: Build
        run: npm run build --verbose
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
          NEXT_PUBLIC_GA4_ID: ${{ secrets.NEXT_PUBLIC_GA4_ID }}
          NEXT_PUBLIC_CALENDLY_LINK: ${{ secrets.NEXT_PUBLIC_CALENDLY_LINK }}
          NEXT_PUBLIC_CALENDLY_EMBED_URL: ${{ secrets.NEXT_PUBLIC_CALENDLY_EMBED_URL }}

      # Debug step to verify environment variables (without exposing sensitive values)
      - name: Debug Environment Variables
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Checking environment variables..."
          echo "SUPABASE_URL is set: ${{ secrets.SUPABASE_URL != '' }}"
          echo "VERCEL_TOKEN is set: ${{ secrets.VERCEL_TOKEN != '' }}"
          echo "VERCEL_ORG_ID is set: ${{ secrets.VERCEL_ORG_ID != '' }}"
          echo "VERCEL_PROJECT_ID is set: ${{ secrets.VERCEL_PROJECT_ID != '' }}"
          echo "RESEND_API_KEY is set: ${{ secrets.RESEND_API_KEY != '' }}"
          echo "EMAIL_FROM is set: ${{ secrets.EMAIL_FROM != '' }}"
          echo "EMAIL_TO is set: ${{ secrets.EMAIL_TO != '' }}"
          echo "ZAPIER_WEBHOOK_URL is set: ${{ secrets.ZAPIER_WEBHOOK_URL != '' }}"
          
          # Test Vercel CLI
          echo "Testing Vercel CLI..."
          npx vercel --version || echo "Vercel CLI not available"

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-comment: false
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          ZAPIER_WEBHOOK_URL: ${{ secrets.ZAPIER_WEBHOOK_URL }} 